### PR TITLE
fixed incorrect linked typedef

### PR DESCRIPTION
**Pull request by chinghwayu**
This fixes the broken wire cause by linking to "Test Suite Attribute Values.ctl" rather than "Test Suites Attribute Values.ctl" in the JUnit Results API package.
DCO-1.1-Signed-off-by: Ching-Hwa Yu <cyu@chinghwayu.com> (github: chinghwayu)

### CODE REVIEW

**Comment by pollockm** [comment]
Thanks!  Posting fixed build momentarily.

**Comment by pollockm** [comment]
Did you have the updated version of the Junit Results API as well?  

I think we might be fighting an incompatible versions problem, in which case the fix would be to bump the dependency version on JUnit Results API to the one that deleted the other typedef.

**Comment by pollockm** [comment]
Or it might be a bug on the JUnit result API...the release here was a port of what was in our perforce server.  I'll verify correctness of that one as well.

**Comment by pollockm** [comment]
Try the new version in the release.  My system is happy with that and the version here: https://github.com/NISystemsEngineering/LV-JUnit/releases/tag/1.0.1
(edited link to be more precise)

**Comment by chinghwayu** [comment]
ah ok, that was it.

**Pull request merged**
